name: null
channels:
- defaults
dependencies:
- Pillow==6.2.1
- appdirs==1.4.3
- certifi==2019.11.28
- chardet==3.0.4
- idna==2.8
- pip==19.3.1
- requests==2.22.0
- setuptools==40.8.0
- tqdm==4.40.2
- urllib3==1.25.7
- pip:
  - requests-futures==1.0.0
  - websockets==6.0
  - wget==3.2
  - pyee==6.0.0
  - pyppeteer==0.0.25
